"""Stage 2.4: the displayed 'already generated' list is BOUNDED (NashSU parity).

NashSU feeds a bounded rolling digest (trimLongText(globalDigest, MAX)) into each
chunk's prompt — never the full accumulated history. Our analogue is the
``generated_slugs`` list: it must still drive per-concept SKIP membership checks
and the Linkable list at FULL size (dedup quality), but the human-readable
"Pages already generated by previous chunks (SKIP these)" block shown to the LLM
must be capped so a long book's late chunks don't carry an ever-growing prompt.
"""
from __future__ import annotations

import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import _core  # noqa: E402
import _stage_2_4_generation as gen  # noqa: E402


def _make_config(tmp: Path) -> _core.Config:
    return _core.Config(
        wiki_root=tmp, raw_root=tmp / "raw",
        wiki_dir=tmp / "wiki", runtime_dir=tmp / "rt",
        cache_path=tmp / "rt" / "ingest-cache.json",
        progress_dir=tmp / "rt" / "ingest-progress",
        extract_tmp_dir=tmp / "rt" / "extract-tmp",
        llm_model="m",
        caption_api_key="", caption_base_url="x",
        caption_model="c", chunk_overlap=3000,
        source_budget=100000, target_chars=60000, target_tokens=30000,
        max_tokens=8192, conversation_prefix="ab12cd34",
    )


class TestGeneratedSlugsDisplayCap(unittest.TestCase):
    def _build(self, tmp: Path, generated_slugs, chunk_analysis=None):
        cfg = _make_config(tmp)
        cfg.wiki_dir.mkdir(parents=True, exist_ok=True)
        cfg.raw_root.mkdir(parents=True, exist_ok=True)
        return gen._stage_2_4_build_prompt(
            chunk_analysis or {"concepts_found": [], "entities_found": []},
            "chunk text",
            1,
            cfg.raw_root / "book.pdf",
            cfg,
            generated_slugs=list(generated_slugs),
        )

    def test_small_list_shown_in_full(self):
        with tempfile.TemporaryDirectory() as d:
            # generated_slugs are stored as bare stems (Path(path).stem), no prefix
            slugs = [f"slug-{i}" for i in range(5)]
            prompt = self._build(Path(d), slugs)
            for s in slugs:
                self.assertIn(s, prompt)
            self.assertNotIn("omitted", prompt)

    @staticmethod
    def _skip_section(prompt: str) -> str:
        start = prompt.index("# Pages already generated by previous chunks")
        end = prompt.index("# Existing wiki pages that overlap", start)
        return prompt[start:end]

    def test_large_list_display_capped(self):
        with tempfile.TemporaryDirectory() as d:
            slugs = [f"slug-{i:03d}" for i in range(60)]
            prompt = self._build(Path(d), slugs)
            skip = self._skip_section(prompt)
            # most-recent slug shown in the SKIP block
            self.assertIn("slug-059", skip)
            # oldest slug dropped from the displayed SKIP block (it still lives
            # in the Linkable list, so linking is preserved)
            self.assertNotIn("slug-000", skip)
            # an omission marker tells the LLM the rest live in the Linkable list
            self.assertIn("omitted", skip)

    def test_membership_skip_survives_display_cap(self):
        """Quality guard: a concept covered by an OLD (display-dropped) chunk is
        still marked ALREADY COVERED so it is NOT regenerated."""
        with tempfile.TemporaryDirectory() as d:
            old_slugs = [f"slug-{i:03d}" for i in range(60)]
            # chunk re-surfaces a concept whose slug == an old, display-dropped one
            chunk_analysis = {
                "concepts_found": [
                    {"name": "Slug 000", "definition": "x", "importance": "core"},
                ],
                "entities_found": [],
            }
            prompt = self._build(Path(d), old_slugs, chunk_analysis)
            # slugify("Slug 000") == "slug-000" → present in old_slugs → SKIP
            self.assertIn("ALREADY COVERED — SKIP", prompt)


class TestLinkableNeverDropsMustLinkTargets(unittest.TestCase):
    """Regression (book-2 re-ingest): the Linkable-pages list was sorted then
    truncated to 300, so an ALREADY-COVERED target (from Stage 2.3 existing_refs)
    that sorts late was dropped from the displayed list — yet the ALREADY-COVERED
    instruction still told the LLM to wikilink to it → a link absent from the
    allowed list. Must-link targets (this chunk's slugs, prior-chunk slugs,
    existing_refs targets, related pages) must NEVER be dropped by the cap."""

    def test_existing_ref_target_survives_cap(self):
        with tempfile.TemporaryDirectory() as d:
            tmp = Path(d)
            cfg = _make_config(tmp)
            cfg.wiki_dir.mkdir(parents=True, exist_ok=True)
            cfg.raw_root.mkdir(parents=True, exist_ok=True)
            # 200 background existing pages + 150 this-chunk concepts → >300 total,
            # all sorting BEFORE the target so the old [:300] cap drops it.
            bg = [f"concepts/aaa-{i:04d}" for i in range(200)]
            this_chunk = [{"name": f"Concept Aab {i:04d}", "definition": "x",
                           "importance": "core"} for i in range(150)]
            orig = gen.list_existing_slugs
            gen.list_existing_slugs = lambda config: list(bg)
            try:
                prompt = gen._stage_2_4_build_prompt(
                    {"concepts_found": this_chunk, "entities_found": []},
                    "chunk text", 1, cfg.raw_root / "book.pdf", cfg,
                    existing_refs={"Zeta Theorem": ["concepts/zzz-target"]},
                )
            finally:
                gen.list_existing_slugs = orig
            # The ALREADY-COVERED target must appear in the Linkable pages list.
            start = prompt.index("# Linkable pages")
            linkable = prompt[start:]
            self.assertIn("concepts/zzz-target", linkable)


if __name__ == "__main__":
    unittest.main()
