"""Regression tests for Stage 3.4 image injection following the page's own
language instead of hardcoding Chinese boilerplate (2026-07-15 KB policy:
every page is Chinese or English — see _language.get_output_language).

Bug: the "## Embedded Images" section always appended a Chinese count line
and a Chinese attribution line, even onto English-body source pages (e.g.
"Radar UAV DCT Survey - 2024 - Ali.md"), mixing Chinese boilerplate into an
otherwise all-English page.

Run:
    python3 -m unittest tests.test_stage_3_4_inject_images   # from scripts/
"""
from __future__ import annotations

import json
import sys
import tempfile
import unittest
from pathlib import Path

_SCRIPTS_DIR = Path(__file__).resolve().parent.parent
if str(_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_DIR))

import _core  # noqa: E402
from _stage_3_4_inject_images import stage_3_4_inject_images  # noqa: E402

_ENGLISH_BODY = (
    "---\ntitle: x\n"
    'sources: ["raw/Paper/01_反无人机探测与识别/book.pdf"]\n'
    "---\n\n"
    "## Paper Summary\n\n"
    "This paper presents a new method for detecting drones using radar "
    "returns and machine learning classifiers trained on real flight data.\n"
)
_CHINESE_BODY = (
    "---\ntitle: x\n"
    'sources: ["raw/Paper/01_反无人机探测与识别/book.pdf"]\n'
    "---\n\n"
    "## 论文摘要\n\n"
    "本文提出了一种基于雷达回波和机器学习分类器的无人机检测新方法，"
    "并在真实飞行数据上进行了训练和验证。\n"
)


def _make_config(tmp: Path) -> _core.Config:
    (tmp / "wiki").mkdir(parents=True, exist_ok=True)
    (tmp / "raw").mkdir(parents=True, exist_ok=True)
    return _core.Config(
        wiki_root=tmp, raw_root=tmp / "raw",
        wiki_dir=tmp / "wiki", runtime_dir=tmp / "rt",
        cache_path=tmp / "rt" / "ingest-cache.json",
        progress_dir=tmp / "rt" / "ingest-progress",
        extract_tmp_dir=tmp / "rt" / "extract-tmp",
        llm_model="m",
        caption_api_key="", caption_base_url="x",
        caption_model="glm-5v-turbo", chunk_overlap=3000,
        source_budget=100000, target_chars=60000, target_tokens=30000,
        max_tokens=8192, conversation_prefix="ab12cd34",
    )


def _run(
    tmp: Path,
    body: str,
    source_type: str = "Paper",
    images: list[dict] | None = None,
) -> str:
    config = _make_config(tmp)
    raw_file = (
        config.raw_root / source_type / "01_反无人机探测与识别" / "book.pdf"
    )
    raw_file.parent.mkdir(parents=True, exist_ok=True)
    raw_file.write_bytes(b"%PDF-fake")

    source_rel = raw_file.relative_to(config.raw_root).with_suffix(".md")
    source_path = config.wiki_dir / "sources" / source_rel
    source_path.parent.mkdir(parents=True, exist_ok=True)
    source_path.write_text(body, encoding="utf-8")

    media_dir = config.wiki_dir / "media" / source_rel.with_suffix("")
    media_dir.mkdir(parents=True, exist_ok=True)
    default_images = [
        {"page": 0, "filename": "p0000-mineru_abc.jpg", "img_idx_in_page": 0},
    ]
    manifest = {
        "images": default_images if images is None else images,
    }
    (media_dir / "_manifest.json").write_text(json.dumps(manifest), encoding="utf-8")

    stage_3_4_inject_images(config, raw_file, source_path)
    return source_path.read_text(encoding="utf-8")


class TestInjectImagesLanguage(unittest.TestCase):
    def test_english_body_gets_english_boilerplate(self):
        with tempfile.TemporaryDirectory() as d:
            result = _run(Path(d), _ENGLISH_BODY)
        self.assertIn("This paper contains 1 extracted figure.", result)
        self.assertIn("Images extracted by minerU VLM; captions generated by", result)
        self.assertNotIn("本书共抽出", result)
        self.assertNotIn("图片由", result)

    def test_chinese_body_gets_chinese_boilerplate(self):
        with tempfile.TemporaryDirectory() as d:
            result = _run(Path(d), _CHINESE_BODY)
        self.assertIn("本文共抽出 1 张图表。", result)
        self.assertIn("图片由 minerU VLM 提取，caption 由", result)
        self.assertNotIn("This document contains", result)

    def test_book_uses_book_specific_noun(self):
        with tempfile.TemporaryDirectory() as d:
            english = _run(Path(d), _ENGLISH_BODY, source_type="Book")
        with tempfile.TemporaryDirectory() as d:
            chinese = _run(Path(d), _CHINESE_BODY, source_type="Book")
        self.assertIn("This book contains 1 extracted figure.", english)
        self.assertIn("本书共抽出 1 张图表。", chinese)

    def test_structural_headings_stay_english_regardless_of_body_language(self):
        # "## Embedded Images" / "### Page N" are structural markup, not
        # prose — they must stay English even on a Chinese-body page (matches
        # the rest of the pipeline's FILE-block convention
        # only localizes prose vocabulary, never structural headings).
        with tempfile.TemporaryDirectory() as d:
            result = _run(Path(d), _CHINESE_BODY)
        self.assertIn("## Embedded Images", result)
        self.assertIn("### Page 1", result)
        self.assertNotIn("### Page 0", result)

    def test_manifest_page_indices_render_as_one_based_source_pages(self):
        images = [
            {"page": 20, "filename": "p0020-mineru_late.jpg", "img_idx_in_page": 0},
            {"page": 0, "filename": "p0000-mineru_first.jpg", "img_idx_in_page": 0},
        ]
        with tempfile.TemporaryDirectory() as d:
            result = _run(Path(d), _ENGLISH_BODY, images=images)
        self.assertIn("### Page 1", result)
        self.assertIn("### Page 21", result)
        self.assertLess(result.index("### Page 1\n"), result.index("### Page 21\n"))

    def test_unpaged_images_render_under_document_after_numbered_pages(self):
        images = [
            {"page": None, "filename": "md_001_diagram.png"},
            {"page": 1, "filename": "p0001-mineru_page.jpg"},
        ]
        with tempfile.TemporaryDirectory() as d:
            result = _run(Path(d), _ENGLISH_BODY, images=images)
        self.assertIn("### Page 2", result)
        self.assertIn("### Document", result)
        self.assertNotIn("### Page None", result)
        self.assertLess(
            result.index("### Page 2\n"), result.index("### Document\n")
        )

    def test_negative_manifest_page_index_fails_loud(self):
        images = [{"page": -1, "filename": "p-001-mineru_bad.jpg"}]
        with tempfile.TemporaryDirectory() as d:
            with self.assertRaisesRegex(RuntimeError, "null or a non-negative integer"):
                _run(Path(d), _ENGLISH_BODY, images=images)


if __name__ == "__main__":
    unittest.main()
