#!/usr/bin/env python3
"""
_source_lifecycle.py — Source lifecycle management (NashSU source-lifecycle.ts parity).

delete_source(): removes source page, cache entry, derived concept/entity pages
                 that are exclusively attributable to this source.
list_source_pages(): list all pages derived from a given source.
"""
from __future__ import annotations

import json, shutil, time
from pathlib import Path

from _paths import detect_runtime_dir, media_slug
from _core import source_cache_key
from _schema import (
    source_slug_from_raw_path,
    load_schema_md,
    schema_folders,
    BASE_PAGE_DIRS,
)
from _frontmatter_array import parse_frontmatter_array
from _embedding_store import remove_page_embeddings
from _progress import file_sha256, stages_path
from _ingest_events import snapshot_source_page_times


def delete_source(raw_file: Path, config, dry_run: bool = False, keep_media: bool = False) -> int:
    """Delete a source and its derived content. Returns count of files removed.

    When ``dry_run`` is True, NOTHING is written or deleted — each action is
    printed with a ``[dry-run]`` marker and the function returns the count that
    WOULD be removed. (Previously ``--delete --dry-run`` ignored dry_run because
    the delete branch ran before ingest.py's dry_run guard — it actually deleted.)

    ``keep_media`` (2026-07-10): skip removing ``wiki/media/<slug>/`` entirely,
    for a re-ingest that only wants to redo Stage 2.2+ analysis while reusing
    already-good OCR/images/captions. Unlike the source/concept/entity pages
    (already backed up to ``page-history/`` below), the media directory has NO
    separate cache elsewhere — minerU's image harvest runs inline with the same
    API call as text extraction, so once deleted, images/captions can only be
    regenerated by a full re-call, not restored. Even when ``keep_media`` is
    False, the media directory is now backed up first (mirroring the existing
    page-history pattern) so a `--delete` run is never irrecoverable by default.

    Completed-run events are never deleted. Before removing a normal source
    page, an identity-scoped content/time baseline is saved so the next run can
    preserve ``created`` and, when content is identical, ``updated``.
    """
    wiki_root = config.wiki_root
    runtime_dir = detect_runtime_dir(wiki_root)
    tag = "[lifecycle][dry-run]" if dry_run else "[lifecycle]"

    # Resolve source path — must match _ingest_write.py's cache-key algorithm
    # (source_cache_key) exactly, or a write uses one key and a delete looks
    # up another.
    rel = source_cache_key(raw_file, config)

    removed = 0
    deleted_embedding_pages: list[str] = []
    cached_source_hash = ""

    # 1. Delete source page
    # source_slug_from_raw_path() is the canonical path-derivation helper
    # (used by ingest dedup too) — a naive ".pdf" -> ".md" string replace
    # left PPTX/DOCX sources' page paths un-rewritten (extension never
    # became .md), so --delete silently found nothing to remove for them.
    src_path = source_slug_from_raw_path(raw_file, wiki_root)
    if src_path is None:
        src_path = wiki_root / "wiki" / "sources" / Path(rel).with_suffix(".md")
    if src_path.exists():
        try:
            deleted_embedding_pages.append(
                src_path.relative_to(wiki_root / "wiki").as_posix()
            )
        except ValueError:
            pass
        if not dry_run:
            snapshot_source_page_times(
                raw_file,
                config,
                src_path,
                captured_at_ms=int(time.time() * 1000),
            )
            # Backup before delete
            history_dir = wiki_root / "page-history"
            history_dir.mkdir(parents=True, exist_ok=True)
            ts = time.strftime("%Y%m%d-%H%M%S")
            backup = history_dir / f"{ts}_{src_path.name}"
            shutil.copy2(src_path, backup)
            src_path.unlink()
        removed += 1
        print(f"{tag} Deleted source page: {rel}")

    # 2. Remove from ingest cache.
    # Match the cache key case-INSENSITIVELY: the key is stored from whatever
    # casing the raw path had at ingest time (e.g. "paper/..."), but a later
    # rename of the raw dir (e.g. to "Paper/...") makes the exact compare miss,
    # leaving a stale entry that makes the next re-ingest a cache hit (skip).
    cache_path = runtime_dir / "ingest-cache.json"
    if cache_path.exists():
        cache = json.loads(cache_path.read_text())
        entries = cache.get("entries", {})
        cache_key = rel.replace("\\", "/")
        match_key = cache_key if cache_key in entries else next(
            (k for k in entries if k.lower() == cache_key.lower()), None
        )
        if match_key is not None:
            matched_entry = entries.get(match_key)
            if isinstance(matched_entry, dict):
                cached_source_hash = str(matched_entry.get("hash") or "")
            if not dry_run:
                del entries[match_key]
                tmp = cache_path.with_suffix(".tmp")
                tmp.write_text(json.dumps(cache, ensure_ascii=False, indent=2))
                tmp.rename(cache_path)
            removed += 1
            print(f"{tag} Removed cache entry: {match_key}")

    # 2.5. Clear only the flow-control markers for an explicit re-ingest.
    # Keep extraction/progress artifacts (especially with --keep-media), the
    # task manifest, and the append-only event ledger. The next run therefore
    # gets a new run_id while preserving first-ingest history and reusable OCR.
    source_hashes = {cached_source_hash} if cached_source_hash else set()
    if raw_file.is_file():
        source_hashes.add(file_sha256(raw_file))
    for source_hash in sorted(source_hashes):
        stage_file = stages_path(config, source_hash)
        if stage_file.exists():
            if not dry_run:
                stage_file.unlink()
            print(f"{tag} Cleared current completion markers: {stage_file.name}")

    # 3. Clean up derived pages (concepts/entities whose ONLY source is this file)
    source_stem = raw_file.stem
    derived_count = _cleanup_orphan_pages(
        wiki_root,
        source_stem,
        config,
        dry_run=dry_run,
        deleted_page_paths=deleted_embedding_pages,
    )
    removed += derived_count
    if derived_count:
        verb = "Would clean up" if dry_run else "Cleaned up"
        print(f"{tag} {verb} {derived_count} derived pages")

    # 4. Remove deleted pages' vector rows. The files remain the source of
    # truth: this happens only after successful disk deletion and is
    # best-effort/non-critical, matching NashSU removePageEmbedding().
    if deleted_embedding_pages and not dry_run:
        embedding_result = remove_page_embeddings(
            wiki_root, deleted_embedding_pages
        )
        if embedding_result["error"]:
            print(
                f"{tag} Warning: page embedding cleanup failed: "
                f"{embedding_result['error']}"
            )
        elif embedding_result["index_present"]:
            print(
                f"{tag} Removed {embedding_result['rows_removed']} embedding "
                f"chunk row(s) for {embedding_result['matched_pages']} page(s)"
            )

    # 5. Remove media directory (unless keep_media — see docstring)
    slug = media_slug(raw_file, config)
    media_dir = wiki_root / "wiki" / "media" / slug
    if media_dir.exists():
        if keep_media:
            print(f"{tag} Kept media directory (--keep-media): media/{slug}")
        else:
            if not dry_run:
                media_history_dir = wiki_root / "page-history" / "media"
                media_history_dir.mkdir(parents=True, exist_ok=True)
                ts = time.strftime("%Y%m%d-%H%M%S")
                shutil.copytree(media_dir, media_history_dir / f"{ts}_{slug.replace('/', '_')}")
                shutil.rmtree(media_dir)
            removed += 1
            print(f"{tag} Removed media directory: media/{slug}")

    verb = "Would remove" if dry_run else "Total removed"
    print(f"{tag} {verb}: {removed} files/dirs")
    return removed



# schema.md may list folders that aren't LLM-generated per-source page types.
_NON_PAGE_DIRS = {"media", "raw", "page-history", "chats"}


def _cleanup_orphan_pages(
    wiki_root: Path,
    source_stem: str,
    config,
    dry_run: bool = False,
    deleted_page_paths: list[str] | None = None,
) -> int:
    """Remove derived pages whose ONLY source reference is this book.

    Covers concepts, entities, queries, comparisons, findings, methodologies,
    plus any schema-defined typed folders (NashSU schema-driven routing —
    people/, methods/, etc.), so a page routed there by Stage 2.4 is cleaned on
    --delete just like a concept page.
    The single-source test below is the guard: pages with ``sources: []`` or with
    more than one source (hand-authored or multi-source hub pages) never match and
    are correctly preserved. synthesis/thesis are intentionally excluded
    (cross-source higher-order pages, not per-source derived). A finding may
    be grounded in one source, so it follows the same cleanup rule.
    """
    base_types = (
        "concepts", "entities", "queries", "comparisons", "findings",
        "methodology",
    )
    extra = schema_folders(load_schema_md(config)) - BASE_PAGE_DIRS - _NON_PAGE_DIRS
    page_types = base_types + tuple(sorted(extra))

    removed = 0
    history_dir = wiki_root / "page-history"
    for page_type in page_types:
        page_dir = wiki_root / "wiki" / page_type
        if not page_dir.exists():
            continue
        # Recursive: a schema may route a type into a nested folder (a Page
        # Types row of `wiki/concepts/notes/` yields the top-level name
        # `concepts`, and the page really is written to `concepts/notes/`).
        # A single-level glob left every page under such a folder behind on
        # --delete. NashSU walks the tree too (source-lifecycle.ts:433).
        for page in sorted(page_dir.rglob("*.md")):
            page_label = f"{page_type}/{page.relative_to(page_dir).as_posix()}"
            try:
                text = page.read_text()
            except Exception as e:
                print(f"[lifecycle] Skipping unreadable page {page_label} "
                      f"({type(e).__name__}: {e}) — cannot check its sources.")
                continue
            # Naive sources_str.split(",") breaks when a source filename
            # itself contains a comma — use the shared frontmatter-array
            # parser (same fix already applied in _stage_3_write.py).
            sources = parse_frontmatter_array(text, "sources")
            if not sources:
                continue
            # Exact basename-stem match, not substring — "LM2596" must not
            # match a sibling source like "raw/.../LM25960.pdf".
            if len(sources) == 1 and Path(sources[0]).stem == source_stem:
                tag = "[lifecycle][dry-run]" if dry_run else "[lifecycle]"
                if not dry_run:
                    history_dir.mkdir(parents=True, exist_ok=True)
                    ts = time.strftime("%Y%m%d-%H%M%S")
                    # Flatten the nested path into the snapshot name so two
                    # same-stem pages from different subfolders cannot collide.
                    snapshot = page_label.replace("/", "_")
                    shutil.copy2(page, history_dir / f"{ts}_{snapshot}")
                    page.unlink()
                    if deleted_page_paths is not None:
                        deleted_page_paths.append(
                            page.relative_to(wiki_root / "wiki").as_posix()
                        )
                print(f"{tag} Deleted orphan page: {page_label}")
                removed += 1
    return removed
