from __future__ import annotations

from _stage_2_base import *

def _stage_2_4_build_prompt(
    chunk_analysis: dict,
    chunk_text: str,
    chunk_index: int,
    file_path: Path,
    config: Config,
    template: str = "",
    generated_slugs: list[str] | None = None,
    existing_refs: dict | None = None,
    related_pages: list[dict] | None = None,
) -> str:
    """Build prompt to generate concept/entity pages from ONE chunk's analysis.

    Accepts generated_slugs from previously-processed chunks so the LLM can:
      - Skip concepts already covered by earlier chunks
      - Use [[wikilinks]] to reference existing pages
      - Avoid duplicate slug generation
    (NashSU parity: sequential, accumulating context.)
    """
    concepts = chunk_analysis.get("concepts_found", [])
    entities = chunk_analysis.get("entities_found", [])
    existing_slugs = list_existing_slugs(config)
    if generated_slugs is None:
        generated_slugs = []
    existing_refs = existing_refs or {}

    concept_lines = []
    concept_slugs: list[tuple[str, str]] = []  # (name, slug) for wikilink reference
    concept_slug_stems: set[str] = set()  # for entity-dedup (Issue 4)
    for c in concepts:
        if isinstance(c, dict):
            name = c.get("name", "")
            imp = c.get("importance", "core")
            defn = c.get("definition", "")
            details = c.get("key_details", [])
            slug = slugify(name)
            # SKIP when generated by a prior chunk OR when Stage 2.3 found an
            # existing-page overlap. Skipping the overlap concept here keeps its
            # NEW slug out of the linkable list so the LLM links to the EXISTING
            # page instead of a never-generated new slug (broken wikilink).
            if name in existing_refs and existing_refs[name]:
                # Issue 2 fix: show the EXISTING slug as the canonical wikilink
                # target so the LLM links there instead of the never-written
                # concepts/{own-slug} (which would be a broken link).
                existing_slug = existing_refs[name][0]
                concept_lines.append(
                    f"  - {name} → ALREADY COVERED by [[{existing_slug}]]: "
                    f"do NOT generate a page; wikilink ONLY as [[{existing_slug}]] "
                    f"(never [[concepts/{slug}]])"
                )
            elif slug in generated_slugs:
                concept_lines.append(
                    f"  - {name} (slug: concepts/{slug}) [{imp}]: {defn} [ALREADY COVERED — SKIP]"
                )
            else:
                concept_lines.append(
                    f"  - {name} (slug: concepts/{slug}) [{imp}]: {defn}"
                )
                concept_slugs.append((name, f"concepts/{slug}"))
                concept_slug_stems.add(slug)
                for d in details[:3]:
                    concept_lines.append(f"      • {d}")

    # Issue 4: collect prior-chunk concept slug stems too, so an entity sharing
    # a concept's slug is deduped (concept page takes precedence over entity).
    for s in generated_slugs:
        if s.startswith("concepts/"):
            concept_slug_stems.add(s.split("/", 1)[1])

    entity_lines = []
    entity_slugs: list[tuple[str, str]] = []  # (name, slug) for wikilink reference
    for e in entities:
        if isinstance(e, dict):
            name = e.get("name", "")
            role = e.get("role", "")
            sig = e.get("significance", "")
            slug = slugify(name)
            if name in existing_refs and existing_refs[name]:
                existing_slug = existing_refs[name][0]
                entity_lines.append(
                    f"  - {name} → ALREADY COVERED by [[{existing_slug}]]: "
                    f"do NOT generate; wikilink ONLY as [[{existing_slug}]]"
                )
            elif slug in generated_slugs or slug in concept_slug_stems:
                # Issue 4: a concept page for this slug already exists (this chunk
                # or a prior one) — skip the duplicate entity page; wikilink to
                # the concept page instead.
                entity_lines.append(
                    f"  - {name} (slug: entities/{slug}) ({role}): {sig} "
                    f"[DUPLICATE OF CONCEPT concepts/{slug} — SKIP]"
                )
            else:
                entity_lines.append(
                    f"  - {name} (slug: entities/{slug}) ({role}): {sig}"
                )
                entity_slugs.append((name, f"entities/{slug}"))

    concept_str = "\n".join(concept_lines[:100]) if concept_lines else "(none)"
    entity_str = "\n".join(entity_lines[:30]) if entity_lines else "(none)"

    generated_str = "\n".join(f"  - {s}" for s in generated_slugs) if generated_slugs else "(none yet — you are the first chunk)"

    # Build linkable slugs list: all slugs the LLM is allowed to wikilink to.
    linkable = set()
    for _, s in concept_slugs:
        linkable.add(s)
    for _, s in entity_slugs:
        linkable.add(s)
    for s in generated_slugs:
        if "/" in s:
            linkable.add(s)
        else:
            linkable.add(f"concepts/{s}")
            linkable.add(f"entities/{s}")
    for s in existing_slugs[:200]:
        linkable.add(s)
    # Stage 2.3 overlap slugs: these EXISTING pages replace the skipped new
    # concepts/entities, so they MUST be linkable (the LLM is told to wikilink
    # to them instead of regenerating). existing_refs values are bare stems.
    for slugs in existing_refs.values():
        for s in slugs:
            linkable.add(s)
    for rp in (related_pages or []):
        slug = rp.get("slug") if isinstance(rp, dict) else None
        if slug:
            linkable.add(slug)
    linkable_list = sorted(linkable)
    if len(linkable_list) > 300:
        linkable_list = linkable_list[:300]
    linkable_str = "\n".join(f"  - {s}" for s in linkable_list) if linkable_list else "(none)"

    template_section = ""
    if template:
        template_section = f"\n# Document Type\n<template>\n{template[:1500]}\n</template>\n"

    # Stage 2.3 feed-back: concepts in this source that already exist in the wiki.
    # The LLM should wikilink to these instead of regenerating them.
    if existing_refs:
        ref_lines = []
        # Sort for deterministic prompt text → stable conversation-handoff cache
        # key. Without sorting, set/dict iteration order (Python hash randomization)
        # varies across runs, changing the prompt hash and re-prompting Stage 2.4
        # forever (cache never hits on resume).
        for name, slugs in sorted(existing_refs.items()):
            links = ", ".join("[[{}]]".format(s) for s in slugs)
            ref_lines.append("  - {} → already exists as: {}".format(name, links))
        existing_refs_str = "\n".join(ref_lines)
    else:
        existing_refs_str = "(none — this source has no overlap with existing wiki)"

    # Stage 2.2's self-reported connections_to_existing_wiki, resolved against
    # real pages by Stage 2.3 (stage_2_3_resolve_proposed_connections). These
    # are RELATED pages, not duplicates of the new concepts — still generate
    # full new pages, just wikilink to these where relevant in the body.
    if related_pages:
        rel_lines = [
            "  - [[{}]] (relationship: {})".format(rp["slug"], rp.get("relationship", "related"))
            for rp in related_pages
        ]
        related_pages_str = "\n".join(rel_lines)
    else:
        related_pages_str = "(none)"

    # P1 (2026-06-27): ground every page in THIS chunk's raw source text. This is
    # what gives full-concept fidelity for books of ANY size — each chunk's
    # concepts are generated with their exact source passage present, so the model
    # uses the source's own formulas/notation/examples, not training-memory.
    if chunk_text.strip():
        chunk_source_section = (
            "# Source Text for THIS chunk (GROUND EVERY PAGE IN THIS — do not write from memory)\n"
            "Use the source's OWN definitions, formulas, notation, variable names, and\n"
            "worked examples — never substitute a generic/popular version from memory.\n"
            "<source>\n"
            f"{chunk_text}\n"
            "</source>\n\n"
        )
    else:
        chunk_source_section = ""

    return f"""# Role
You are generating wiki pages for ONE chunk of a book. Previous chunks have
already been processed — their pages are listed below. Do NOT regenerate them.

# Source
Book: {file_path.stem}
Chunk: {chunk_index + 1}

{template_section}
{chunk_source_section}# Pages already generated by previous chunks (SKIP these):
{generated_str}

# Existing wiki pages that overlap (Stage 2.3 — DO NOT regenerate; wikilink to them):
{existing_refs_str}

# Related (not duplicate) existing pages — wikilink to these where relevant, but still generate full new pages for the concepts/entities below:
{related_pages_str}

# Concepts found in this chunk (generate a page for each — skip ALREADY COVERED):
{concept_str}

# Entities found in this chunk (generate a page for key ones — skip ALREADY COVERED):
{entity_str}

# Supplementary foundational pages (use sparingly)
If THIS chunk clearly defines or depends on a foundational concept that is NOT in
the lists above AND is NOT in the Linkable pages list below (i.e. no existing page
covers it), you MAY generate a page for it at a new `wiki/concepts/<kebab-slug>.md`
path. Only do this for genuinely page-worthy building blocks the source actually
explains — never for passing mentions. Give it a short, specific kebab-case slug
and a `type: concept` frontmatter like the others. Do NOT [[wikilink]] to any slug
that is not either in the Linkable list or a page you generate in THIS response.

# ⚠️ CRITICAL — START IMMEDIATELY WITH FILE BLOCKS
- Your FIRST line of output MUST be `---FILE:wiki/concepts/...`
- Do NOT write any preamble, introduction, or commentary. IGNORED by parser.

# [[wikilink]] Rules — STRICT
Each concept/entity above includes a slug like (slug: concepts/foo-bar).
This is the EXACT [[wikilink]] you must use — kebab-case with type prefix.

Correct format:
  [[concepts/natural-convection-heat-sink]]  ← kebab-case + concepts/ prefix
  [[entities/bell-labs]]                      ← kebab-case + entities/ prefix

WRONG formats (DO NOT use — these create broken links):
  [[Natural Convection Heat Sink]]  ← Title Case, no prefix = BROKEN
  [[convection]]                    ← missing prefix = BROKEN
  [[concepts/litz-wire.md]]         ← includes .md = BROKEN
  [[cooling technique]]             ← not in linkable list = BROKEN

# Linkable pages (ONLY these [[wikilinks]] are valid):
{linkable_str}

Rules:
1. ONLY use [[wikilinks]] from the "Linkable pages" list above.
2. Use the EXACT slug shown. Do not change case, add words, or invent new ones.
3. For concepts/entities IN THIS CHUNK: use the slug from its "(slug: ...)" label.
4. If no matching slug exists, write the term as PLAIN TEXT with NO [[]].
5. NEVER use `/` in filenames (macOS rejects it). Use "-" instead.
6. Math: $inline$ $$display$$

# Output Format — EXACT
---FILE:wiki/concepts/<slug>.md---
---
type: concept
title: "..."
domain: general
tags: [...]
related: [...]
sources: ["raw/{file_path.relative_to(config.raw_root)}"]
created: {time.strftime('%Y-%m-%d')}
updated: {time.strftime('%Y-%m-%d')}
---

# Title

(content)

---END FILE---
---FILE:wiki/entities/<slug>.md---
(frontmatter + content)
---END FILE---

Generate a page for EVERY concept listed above that is NOT marked [ALREADY COVERED]. Go!
"""


# ── Per-concept fallback (when per-chunk returns 0 blocks) ──

# Maximum concepts per LLM call in fallback mode.
# Above this, concepts are split into multiple calls.
PER_CONCEPT_BATCH_MAX = 4


def _stage_2_4_per_concept_fallback(
    chunk_analyses: list[dict],
    global_digest: dict,
    file_path: Path,
    config: Config,
    template: str = "",
    verbose: bool = False,
    pre_existing_slugs: list[str] | None = None,
) -> tuple[dict, str, list[tuple[str, str]]]:
    """Generate each concept in its own small LLM call.

    Used when per-chunk generation returns 0 FILE blocks (e.g. chunk has
    too many concepts for a single call to complete within max_tokens/timeout).
    Each concept gets a focused prompt with just its definition + context from
    the chunk that found it.

    pre_existing_slugs: slugs already generated by prior per-chunk calls.
    When provided (barrier-free fallback), these concepts are skipped so the
    fallback only generates what was missed — avoids duplicate LLM calls.
    """
    unique_concepts, unique_entities = _stage_2_4_extract_names(chunk_analyses)
    all_file_blocks: list[tuple[str, str]] = []
    all_responses: list[str] = []
    generated_slugs: list[str] = list(pre_existing_slugs) if pre_existing_slugs else []
    gen_tokens = config.compute_max_tokens(8192)
    t0 = time.time()
    total = len(unique_concepts) + len(unique_entities)

    # Build concept→chunk_analysis map for targeted context
    concept_to_chunk: dict[str, int] = {}
    for idx, analysis in enumerate(chunk_analyses):
        for c in analysis.get("concepts_found", []):
            name = c.get("name", c) if isinstance(c, dict) else str(c)
            concept_to_chunk[name] = idx

    print(f"[stage 2.3] Per-concept fallback: {len(unique_concepts)} concepts + "
          f"{len(unique_entities)} entities, {PER_CONCEPT_BATCH_MAX} per batch, "
          f"max_tokens={gen_tokens}")

    n = 0
    existing_slugs = list_existing_slugs(config)

    for concept_name in unique_concepts:
        chunk_idx = concept_to_chunk.get(concept_name, 0)
        analysis = chunk_analyses[chunk_idx] if chunk_idx < len(chunk_analyses) else chunk_analyses[0]

        # Extract concept details from the chunk analysis
        concept_info = None
        for c in analysis.get("concepts_found", []):
            name = c.get("name", c) if isinstance(c, dict) else str(c)
            if name == concept_name:
                concept_info = c if isinstance(c, dict) else {"name": c}
                break

        slug = slugify(concept_name)
        if slug in generated_slugs:
            continue

        prompt = _stage_2_4_build_per_concept_prompt(
            concept_info, slug, file_path, config, global_digest,
            analysis, generated_slugs, existing_slugs, template,
        )

        for attempt in range(3):
            try:
                t_call = time.time()
                response, stop_reason = call_anthropic_protocol(prompt, config, max_tokens=gen_tokens)
                all_responses.append(response)
                blocks = parse_file_blocks(response)
                all_file_blocks.extend(blocks)
                dt = time.time() - t_call
                n += 1
                pct = n * 100 // total
                tag = f" (retry #{attempt})" if attempt > 0 else ""
                print(f"  [concept {n}/{total}] {concept_name[:50]} → "
                      f"{len(blocks)} blocks ({len(response):,} chars, {stop_reason}) "
                      f"{dt:.0f}s [{pct}%]{tag}")
                for path, _content in blocks:
                    s = Path(path).stem.lower().replace(" ", "-").replace("/", "-")
                    if s not in generated_slugs:
                        generated_slugs.append(s)
                break
            except Exception as e:
                if attempt < 2 and _is_retryable_exception(e):
                    wait = _retry_jitter(2.0, attempt)
                    print(f"  [concept {n+1}/{total}] {type(e).__name__} retry in {wait:.1f}s...")
                    time.sleep(wait)
                    continue
                print(f"  [concept {n+1}/{total}] ❌ {e}")
                break

    for entity_name in unique_entities[:min(len(unique_entities), 20)]:
        slug = slugify(entity_name)
        if slug in generated_slugs:
            continue
        prompt = _stage_2_4_build_per_entity_prompt(
            entity_name, slug, file_path, config, global_digest,
            existing_slugs, template,
        )
        for attempt in range(3):
            try:
                response, stop_reason = call_anthropic_protocol(prompt, config, max_tokens=gen_tokens)
                all_responses.append(response)
                blocks = parse_file_blocks(response)
                all_file_blocks.extend(blocks)
                n += 1
                pct = n * 100 // total
                print(f"  [entity {n}/{total}] {entity_name[:50]} → "
                      f"{len(blocks)} blocks ({len(response):,} chars, {stop_reason}) [{pct}%]")
                for path, _content in blocks:
                    s = Path(path).stem.lower().replace(" ", "-").replace("/", "-")
                    if s not in generated_slugs:
                        generated_slugs.append(s)
                break
            except Exception as e:
                if attempt < 2 and _is_retryable_exception(e):
                    time.sleep(_retry_jitter(2.0, attempt))
                    continue
                print(f"  [entity {n+1}/{total}] ❌ {e}")
                break

    # Generate source page from global digest (compact)
    try:
        source_rel = f"sources/{file_path.relative_to(config.raw_root).with_suffix('.md')}"
    except ValueError:
        source_rel = f"sources/{file_path.with_suffix('.md').name}"
    source_prompt = f"""# Role
Generate a source page for this document from the global digest.

# Global Digest
```yaml
{json.dumps(global_digest, ensure_ascii=False, indent=2)[:4000]}
```

# Concepts generated ({len(all_file_blocks)} pages)
{', '.join(Path(p).stem for p, _ in all_file_blocks[:80])}

# Output Format — EXACT
---FILE:wiki/{source_rel}---
(frontmatter type:source + content)
---END FILE---

START IMMEDIATELY with ---FILE:... No preamble.
"""
    try:
        src_response, _ = call_anthropic_protocol(
            source_prompt, config, max_tokens=config.compute_max_tokens(4096))
        all_responses.append(src_response)
        src_blocks = parse_file_blocks(src_response)
        all_file_blocks.extend(src_blocks)
    except Exception as e:
        print(f"  [stage 2.3] Source page generation failed: {e}")

    combined = "\n".join(all_responses)
    concept_blocks = [b for b in all_file_blocks if "concepts/" in b[0]]
    entity_blocks = [b for b in all_file_blocks if "entities/" in b[0]]
    source_blocks = [b for b in all_file_blocks if "sources/" in b[0]]

    print(f"[stage 2.3] Per-concept fallback done — {time.time()-t0:.0f}s, "
          f"{len(all_file_blocks)} blocks ({len(concept_blocks)}c/{len(entity_blocks)}e/{len(source_blocks)}s)")

    analysis = {
        "book_meta": global_digest.get("book_meta", {}),
        "outline": global_digest.get("outline", []),
        "concepts_identified": len(unique_concepts),
        "concepts_generated": len(concept_blocks),
        "entities_generated": len(entity_blocks),
        "source_generated": len(source_blocks) > 0,
        "coverage_pct": round(len(concept_blocks) / max(len(unique_concepts), 1), 2),
        "total_chunks": len(chunk_analyses),
        "method": "per-concept-fallback",
    }
    return analysis, combined, all_file_blocks


def _stage_2_4_build_per_concept_prompt(
    concept_info: dict,
    slug: str,
    file_path: Path,
    config: Config,
    global_digest: dict,
    chunk_analysis: dict,
    generated_slugs: list[str],
    existing_slugs: list[str],
    template: str = "",
) -> str:
    """Build a focused prompt for generating ONE concept page."""
    name = concept_info.get("name", slug)
    definition = concept_info.get("definition", "")
    importance = concept_info.get("importance", "core")
    details = concept_info.get("key_details", [])[:5]

    try:
        raw_rel = str(file_path.relative_to(config.raw_root))
    except ValueError:
        raw_rel = file_path.name

    # Sibling concepts from same chunk (for wikilinks)
    siblings = []
    for c in chunk_analysis.get("concepts_found", []):
        cn = c.get("name", c) if isinstance(c, dict) else str(c)
        if cn != name:
            siblings.append(cn)

    template_section = ""
    if template:
        template_section = f"\n# Document Type\n<template>\n{template[:800]}\n</template>\n"

    return f"""# Role
Generate ONE wiki concept page. Output ONLY this one page, then stop.

{template_section}
# Concept to Generate
- Name: {name}
- Importance: {importance}
- Definition: {definition}
{f"- Key Details: " + "; ".join(details) if details else ""}

# Context from Source
Source: {file_path.stem}
{f"Sibling concepts in this section (use [[wikilinks]]): {', '.join(siblings[:10])}" if siblings else ""}

# Already Generated (skip these — use [[wikilinks]]):
{', '.join(generated_slugs[:50]) or "(none yet)"}

# Existing Wiki Pages (avoid duplicates):
{', '.join(existing_slugs[:50]) or "(none)"}

# ⚠️ CRITICAL — START IMMEDIATELY WITH FILE BLOCK
Your FIRST line MUST be `---FILE:wiki/concepts/{slug}.md---`
Do NOT write preamble, analysis, or commentary. Parser IGNORES non-FILE text.

# Output Format — EXACT
---FILE:wiki/concepts/{slug}.md---
---
type: concept
domain: general
title: "{name}"
tags: [...]
related: []
sources: ["raw/{raw_rel}"]
created: {time.strftime('%Y-%m-%d')}
updated: {time.strftime('%Y-%m-%d')}
---

# {name}

(Detailed content — explain the concept, include key details, use [[wikilinks]])

---END FILE---

Generate the page NOW. Start with ---FILE:...
"""


def _stage_2_4_build_per_entity_prompt(
    entity_name: str,
    slug: str,
    file_path: Path,
    config: Config,
    global_digest: dict,
    existing_slugs: list[str],
    template: str = "",
) -> str:
    """Build a focused prompt for generating ONE entity page."""
    try:
        raw_rel = str(file_path.relative_to(config.raw_root))
    except ValueError:
        raw_rel = file_path.name

    return f"""# Role
Generate ONE wiki entity page. Output ONLY this one page, then stop.

# Entity to Generate
- Name: {entity_name}

# Source
Document: {file_path.stem}

# Existing Wiki Pages (avoid duplicates):
{', '.join(existing_slugs[:50]) or "(none)"}

# ⚠️ CRITICAL — START IMMEDIATELY WITH FILE BLOCK
Your FIRST line MUST be `---FILE:wiki/entities/{slug}.md---`
Do NOT write preamble, analysis, or commentary.

# Output Format — EXACT
---FILE:wiki/entities/{slug}.md---
---
type: entity
domain: general
title: "{entity_name}"
tags: [...]
related: []
sources: ["raw/{raw_rel}"]
created: {time.strftime('%Y-%m-%d')}
updated: {time.strftime('%Y-%m-%d')}
---

# {entity_name}

(Description, significance, key attributes, related concepts using [[wikilinks]])

---END FILE---

Generate the page NOW. Start with ---FILE:...
"""


def _stage_2_4_build_all_prompt(
    chunk_analyses: list[dict],
    file_path: Path,
    config: Config,
    template: str = "",
    existing_refs: dict | None = None,
    related_pages: list[dict] | None = None,
    source_context: str = "",
) -> str:
    """Build ONE generation prompt covering ALL chunks (NashSU single-shot parity).

    Aggregates concepts/entities across every chunk analysis, dedups by slug,
    and asks the LLM to emit FILE blocks for all of them in a single response.
    Replaces the former per-chunk generation loop (Stage 2.4 × N calls → 1 call).

    ``source_context`` (P1, 2026-06-27): raw source text, already trimmed to the
    caller's budget. When present it is injected so the LLM grounds each page in
    the source's OWN wording/formulas/examples instead of generic training-memory
    knowledge — NashSU parity (buildGenerationPrompt feeds trimmed sourceContext).
    Verified via the Hennessy A/B: analysis-only produced a wrong Amdahl's-Law
    formula (the popular p/n form) instead of the book's Fraction_enhanced form.
    """
    existing_refs = existing_refs or {}
    existing_slugs = list_existing_slugs(config)

    seen_concept_slugs: set[str] = set()
    concept_lines: list[str] = []
    concept_slugs: list[tuple[str, str]] = []
    concept_slug_stems: set[str] = set()
    for ca in chunk_analyses:
        if not isinstance(ca, dict) or "error" in ca:
            continue
        for c in ca.get("concepts_found", []):
            if not isinstance(c, dict):
                continue
            name = c.get("name", "")
            slug = slugify(name)
            if not name or slug in seen_concept_slugs:
                continue
            seen_concept_slugs.add(slug)
            imp = c.get("importance", "core")
            defn = c.get("definition", "")
            details = c.get("key_details", [])
            if name in existing_refs and existing_refs[name]:
                existing_slug = existing_refs[name][0]
                concept_lines.append(
                    f"  - {name} → ALREADY COVERED by [[{existing_slug}]]: "
                    f"do NOT generate a page; wikilink ONLY as [[{existing_slug}]] "
                    f"(never [[concepts/{slug}]])"
                )
            else:
                concept_lines.append(f"  - {name} (slug: concepts/{slug}) [{imp}]: {defn}")
                concept_slugs.append((name, f"concepts/{slug}"))
                concept_slug_stems.add(slug)
                for d in details[:3]:
                    concept_lines.append(f"      • {d}")

    seen_entity_slugs: set[str] = set()
    entity_lines: list[str] = []
    entity_slugs: list[tuple[str, str]] = []
    for ca in chunk_analyses:
        if not isinstance(ca, dict) or "error" in ca:
            continue
        for e in ca.get("entities_found", []):
            if not isinstance(e, dict):
                continue
            name = e.get("name", "")
            slug = slugify(name)
            if not name or slug in seen_entity_slugs:
                continue
            seen_entity_slugs.add(slug)
            role = e.get("role", "")
            sig = e.get("significance", "")
            if name in existing_refs and existing_refs[name]:
                existing_slug = existing_refs[name][0]
                entity_lines.append(
                    f"  - {name} → ALREADY COVERED by [[{existing_slug}]]: "
                    f"do NOT generate; wikilink ONLY as [[{existing_slug}]]"
                )
            elif slug in concept_slug_stems:
                entity_lines.append(
                    f"  - {name} (slug: entities/{slug}) ({role}): {sig} "
                    f"[DUPLICATE OF CONCEPT concepts/{slug} — SKIP]"
                )
            else:
                entity_lines.append(f"  - {name} (slug: entities/{slug}) ({role}): {sig}")
                entity_slugs.append((name, f"entities/{slug}"))

    concept_str = "\n".join(concept_lines[:200]) if concept_lines else "(none)"
    entity_str = "\n".join(entity_lines[:60]) if entity_lines else "(none)"

    linkable = set()
    for _, s in concept_slugs:
        linkable.add(s)
    for _, s in entity_slugs:
        linkable.add(s)
    for s in existing_slugs[:200]:
        linkable.add(s)
    for slugs in existing_refs.values():
        for s in slugs:
            linkable.add(s)
    for rp in (related_pages or []):
        slug = rp.get("slug") if isinstance(rp, dict) else None
        if slug:
            linkable.add(slug)
    linkable_list = sorted(linkable)[:300]
    linkable_str = "\n".join(f"  - {s}" for s in linkable_list) if linkable_list else "(none)"

    template_section = ""
    if template:
        template_section = f"\n# Document Type\n<template>\n{template[:1500]}\n</template>\n"

    if existing_refs:
        ref_lines = []
        for name, slugs in sorted(existing_refs.items()):
            links = ", ".join("[[{}]]".format(s) for s in slugs)
            ref_lines.append("  - {} → already exists as: {}".format(name, links))
        existing_refs_str = "\n".join(ref_lines)
    else:
        existing_refs_str = "(none — this source has no overlap with existing wiki)"

    if related_pages:
        rel_lines = [
            "  - [[{}]] (relationship: {})".format(rp["slug"], rp.get("relationship", "related"))
            for rp in related_pages
        ]
        related_pages_str = "\n".join(rel_lines)
    else:
        related_pages_str = "(none)"

    if source_context.strip():
        source_section = (
            "\n# Source Text (GROUND EVERY PAGE IN THIS — do not write from memory)\n"
            "The following is the raw source text (trimmed to budget). For every page:\n"
            "- Use the SOURCE'S OWN definitions, formulas, notation, variable names,\n"
            "  and worked examples — NOT the popular/textbook version from your memory.\n"
            "- If the source frames a concept a specific way (e.g. a particular formula\n"
            "  or set of variables), reproduce THAT framing; do not substitute a\n"
            "  generic equivalent.\n"
            "- Prefer the source's concrete numbers/examples over invented ones.\n"
            "- If a concept below is not covered by this excerpt, generate it from its\n"
            "  analysis entry as usual.\n"
            "<source>\n"
            f"{source_context}\n"
            "</source>\n"
        )
    else:
        source_section = ""

    return f"""# Role
You are generating wiki pages for ALL chunks of a book in ONE pass. The complete
concept/entity lists aggregated across every chunk are below. Generate a page for
each one that is NOT marked ALREADY COVERED — in a single response.

# Source
Book: {file_path.stem}
Chunks: {len(chunk_analyses)}
{template_section}{source_section}
# Existing wiki pages that overlap (Stage 2.3 — DO NOT regenerate; wikilink to them):
{existing_refs_str}

# Related (not duplicate) existing pages — wikilink to these where relevant, but still generate full new pages for the concepts/entities below:
{related_pages_str}

# Concepts found across ALL chunks (generate a page for each — skip ALREADY COVERED):
{concept_str}

# Entities found across ALL chunks (generate a page for key ones — skip ALREADY COVERED / DUPLICATE):
{entity_str}

# Supplementary foundational pages (use sparingly)
If the source clearly defines a foundational concept NOT in the lists above AND NOT
in the Linkable pages list below, you MAY generate a page for it at a new
`wiki/concepts/<kebab-slug>.md`. Only for genuinely page-worthy building blocks the
source actually explains — never for passing mentions. Do NOT [[wikilink]] to any
slug that is not either in the Linkable list or a page you generate in THIS response.

# ⚠️ CRITICAL — START IMMEDIATELY WITH FILE BLOCKS
- Your FIRST line of output MUST be `---FILE:wiki/concepts/...`
- Do NOT write any preamble, introduction, or commentary. IGNORED by parser.

# [[wikilink]] Rules — STRICT
Each concept/entity above includes a slug like (slug: concepts/foo-bar).
This is the EXACT [[wikilink]] you must use — kebab-case with type prefix.

Correct:  [[concepts/natural-convection-heat-sink]]  [[entities/bell-labs]]
WRONG:    [[Natural Convection Heat Sink]]  [[convection]]  [[concepts/litz-wire.md]]

# Linkable pages (ONLY these [[wikilinks]] are valid):
{linkable_str}

Rules:
1. ONLY use [[wikilinks]] from the "Linkable pages" list above.
2. Use the EXACT slug shown. Do not change case, add words, or invent new ones.
3. For concepts/entities below: use the slug from its "(slug: ...)" label.
4. If no matching slug exists, write the term as PLAIN TEXT with NO [[]].
5. NEVER use `/` in filenames (macOS rejects it). Use "-" instead.
6. Math: $inline$ $$display$$

# Output Format — EXACT
---FILE:wiki/concepts/<slug>.md---
---
type: concept
title: "..."
domain: general
tags: [...]
related: [...]
sources: ["raw/{file_path.relative_to(config.raw_root)}"]
created: {time.strftime('%Y-%m-%d')}
updated: {time.strftime('%Y-%m-%d')}
---

# Title

(content)

---END FILE---
---FILE:wiki/entities/<slug>.md---
(frontmatter + content)
---END FILE---

Generate a page for EVERY concept listed above that is NOT marked [ALREADY COVERED], in ONE response. Go!
"""


def stage_2_4_generate_all(
    chunk_analyses: list[dict],
    file_path: Path,
    config: Config,
    template: str = "",
    verbose: bool = False,
    existing_refs: dict | None = None,
    related_pages: list[dict] | None = None,
    source_context: str = "",
) -> tuple[list[tuple[str, str]], list[str], str | None]:
    """Single-shot generation: ONE LLM call for all chunks (NashSU parity, 2026-06-27).

    Replaces the per-chunk generation loop. Returns (file_blocks, generated_slugs,
    stop_reason). The per-concept fallback (caller-side) catches any concepts the
    single shot missed, including output-truncation gaps.
    """
    valid = [ca for ca in chunk_analyses if isinstance(ca, dict) and "error" not in ca]
    has_concepts = any(ca.get("concepts_found") for ca in valid)
    has_entities = any(ca.get("entities_found") for ca in valid)
    if not has_concepts and not has_entities:
        print("  [generate-all] no concepts or entities across all chunks — skipped")
        return [], [], None

    prompt = _stage_2_4_build_all_prompt(
        chunk_analyses, file_path, config, template,
        existing_refs=existing_refs, related_pages=related_pages,
        source_context=source_context,
    )
    gen_tokens = config.compute_max_tokens(16384)

    for attempt in range(4):
        try:
            t0 = time.time()
            if attempt == 0:
                print("  [generate-all] single-shot generating (all chunks)...", flush=True)
            response, stop_reason = call_anthropic_protocol(
                prompt, config, max_tokens=gen_tokens, label="single-shot generation")
            blocks = parse_file_blocks(response)
            dt = time.time() - t0
            generated_slugs: list[str] = []
            for path, _ in blocks:
                slug = Path(path).stem.lower().replace(" ", "-").replace("/", "-")
                if slug not in generated_slugs:
                    generated_slugs.append(slug)
            tag = f" (retry #{attempt})" if attempt > 0 else ""
            print(f"  [generate-all] OK{tag} — {len(blocks)} blocks "
                  f"({len(response):,} chars, {stop_reason}) {dt:.0f}s")
            sr = str(stop_reason).lower()
            if "length" in sr or "max_tokens" in sr:
                print(f"  [generate-all] ⚠️ response truncated ({stop_reason}) — "
                      f"some pages may be missing; per-concept fallback will fill gaps "
                      f"if zero concept blocks result.")
            if verbose:
                print(f"    response: {response[:500]}...")
            return blocks, generated_slugs, stop_reason
        except Exception as e:
            if attempt < 3 and _is_retryable_exception(e):
                wait = _retry_jitter(2.0, attempt)
                print(f"  [generate-all] {type(e).__name__} retry {attempt+1}/4 — {wait:.1f}s...")
                time.sleep(wait)
                continue
            print(f"  [generate-all] FAILED: {e}")
            return [], [], None
    return [], [], None


def stage_2_4_generate_chunk(
    analysis: dict,
    chunk_idx: int,
    generated_slugs: list[str],
    file_path: Path,
    config: Config,
    template: str = "",
    verbose: bool = False,
    chunk_text: str = "",
    existing_refs: dict | None = None,
    related_pages: list[dict] | None = None,
) -> list[tuple[str, str]]:
    """Generate FILE blocks for a single chunk (extracted from stage_2_per_chunk_generation).

    Used by the analyze→generate pipeline in _do_prepare. ``existing_refs``
    (Stage 2.3 output: {concept_name: [wiki_slugs]}) is forwarded to the prompt
    so the LLM wikilinks to existing pages instead of regenerating them.
    ``related_pages`` (Stage 2.3's stage_2_3_resolve_proposed_connections
    output: [{"slug": ..., "relationship": ...}]) is forwarded so the LLM
    wikilinks new pages to genuinely *related* (not duplicate) existing pages.

    Returns list of (path, content) tuples.  Caller should append slugs to
    generated_slugs from the returned paths.
    """
    concepts_n = len(analysis.get("concepts_found", []))
    entities_n = len(analysis.get("entities_found", []))
    if concepts_n == 0 and entities_n == 0:
        print(f"  [chunk {chunk_idx+1}] (no concepts or entities — skipped)")
        return []

    prompt = _stage_2_4_build_prompt(
        analysis, chunk_text, chunk_idx, file_path, config, template,
        generated_slugs=generated_slugs, existing_refs=existing_refs,
        related_pages=related_pages,
    )
    gen_tokens = config.compute_max_tokens(16384)

    for attempt in range(4):
        try:
            t0 = time.time()
            if attempt == 0:
                print(f"  [chunk {chunk_idx+1}] generating ({concepts_n}c/{entities_n}e)...",
                      flush=True)
            response, stop_reason = call_anthropic_protocol(prompt, config, max_tokens=gen_tokens, label=f"chunk {chunk_idx+1} generation")
            blocks = parse_file_blocks(response)
            dt = time.time() - t0
            tag = f" (retry #{attempt})" if attempt > 0 else ""
            print(f"  [chunk {chunk_idx+1}] generate OK{tag} — "
                  f"{concepts_n}c/{entities_n}e → {len(blocks)} blocks "
                  f"({len(response):,} chars, {stop_reason}) {dt:.0f}s")
            if verbose:
                print(f"    response: {response[:500]}...")
            return blocks

        except Exception as e:
            if attempt < 3 and _is_retryable_exception(e):
                wait = _retry_jitter(2.0, attempt)
                err_label = type(e).__name__
                print(f"  [chunk {chunk_idx+1}] generate {err_label} retry {attempt+1}/4"
                      f" — {wait:.1f}s...")
                time.sleep(wait)
                continue
            print(f"  [chunk {chunk_idx+1}] generate FAILED: {e}")
            return []



# ---------- Stage 2: Synthesis (legacy, for small books) ----------

def _stage_2_4_build_image_reference_section(file_path: Path, config: Config) -> str:
    """Build a compact list of available images for the Stage 2 prompt."""
    slug = _stage_1_2_media_slug(file_path, config)
    media_dir = config.wiki_dir / "media" / slug
    if not media_dir.exists():
        return "（本书无提取图片）\n"

    manifest_path = media_dir / "_manifest.json"
    captioned = 0
    total = 0
    sample_lines: list[str] = []

    if manifest_path.exists():
        m = json.loads(manifest_path.read_text(encoding="utf-8"))
        images = m.get("images", [])
        # Legacy guard: skip full-page renders from old ingests (source:"page-render").
        # Current pipeline no longer produces these.
        images = [i for i in images if i.get("source") != "page-render"]
        total = len(images)
        for img in sorted(images, key=lambda x: (x["page"], x.get("img_idx_in_page", 0)))[:60]:
            cap_path = media_dir / (img["filename"] + ".caption.txt")
            cap = cap_path.read_text(encoding="utf-8").strip()[:70] if cap_path.exists() else ""
            sample_lines.append(f"  p{img['page']} `{img['filename']}`: {cap}")
            if cap:
                captioned += 1
    else:
        # Loose files (minerU, old cloud OCR without manifest)
        for f in sorted(media_dir.iterdir()):
            if f.suffix.lower() in (".jpg", ".jpeg", ".png"):
                # Legacy guard: skip old full-page renders (pNNNN.jpg without
                # -mineru_ / -fig suffix). Current pipeline no longer produces these.
                stem = f.stem
                if re.match(r"^p\d{4}$", stem) and "-mineru_" not in stem:
                    continue
                total += 1
                cap_path = media_dir / (f.name + ".caption.txt")
                cap = cap_path.read_text(encoding="utf-8").strip()[:70] if cap_path.exists() else ""
                if total <= 60:
                    sample_lines.append(f"  `{f.name}`: {cap}")
                if cap:
                    captioned += 1

    if total == 0:
        return "（本书无提取图片）\n"

    section = f"本书共 {total} 张图（{captioned} 有caption）。图片位于 wiki/media/{slug}/。\n"
    section += "在 concept/entity 页面中用 ![](media/{}/filename) 引用相关图片。\n".format(slug)
    section += "关键图片示例：\n"
    section += "\n".join(sample_lines[:60])
    if total > 60:
        section += f"\n  ... （共 {total} 张，仅列前 60）"
    return section + "\n"



def _stage_2_4_extract_names(chunk_analyses: list[dict]) -> tuple[list[str], list[str]]:
    """Extract deduplicated concept and entity names from chunk analyses."""
    all_concepts: list[str] = []
    all_entities: list[str] = []
    for a in chunk_analyses:
        for c in a.get("concepts_found") or []:
            name = c.get("name", c) if isinstance(c, dict) else str(c)
            all_concepts.append(name)
        for e in a.get("entities_found") or []:
            name = e.get("name", e) if isinstance(e, dict) else str(e)
            all_entities.append(name)
    seen_c: set[str] = set()
    unique_concepts = [x for x in all_concepts if not (x in seen_c or seen_c.add(x))]  # type: ignore[func-returns-value]
    seen_e: set[str] = set()
    unique_entities = [x for x in all_entities if not (x in seen_e or seen_e.add(x))]  # type: ignore[func-returns-value]
    return unique_concepts, unique_entities


